apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: argon-api
  name: argon-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: argon-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: argon-api
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: argon-api
        - secretRef:
            name: argon-api
        image: '{{ .Values.images.argonapi }}'
        imagePullPolicy: IfNotPresent
        name: argon-api
        ports:
        - containerPort: 5001
          name: http
        - containerPort: 5001
          name: https
      terminationGracePeriodSeconds: 180