apiVersion: v1
data:
  ConnectionStrings__DefaultConnection: SG9zdD1wZztQb3J0PTU0MzI7VXNlcm5hbWU9cG9zdGdyZXM7UGFzc3dvcmQ9cG9zdGdyZXM7RGF0YWJhc2U9YXBpRGI=
  ConnectionStrings__cache: Y2FjaGU6NjM3OQ==
  ConnectionStrings__clickhouse: aHR0cDovL3Bvc3RncmVzOnBvc3RncmVzQGNsaWNraG91c2U6ODEyMw==
  ConnectionStrings__nats: bmF0czovL25hdHM6NDIyMg==
kind: Secret
metadata:
  annotations: {}
  labels:
    app: argon-api
  name: argon-api
type: Opaque