apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: argon-entry
  name: argon-entry
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: argon-entry
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        app: argon-entry
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: argon-entry
        image: '{{ .Values.images.argonentry }}'
        imagePullPolicy: IfNotPresent
        name: argon-entry
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
      terminationGracePeriodSeconds: 180