apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: cache
  name: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  serviceName: cache
  template:
    metadata:
      annotations: {}
      labels:
        app: cache
    spec:
      containers:
      - args:
        - --save
        - "60"
        - "1"
        envFrom:
        - configMapRef:
            name: cache
        image: '{{ .Values.images.cache }}'
        imagePullPolicy: IfNotPresent
        name: cache
        ports:
        - containerPort: 6379
          name: tcp
        volumeMounts:
        - mountPath: /data
          name: apphost-feed4158f1-cache-data
      terminationGracePeriodSeconds: 180
  volumeClaimTemplates:
  - metadata:
      name: apphost-feed4158f1-cache-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi