apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: clickhouse
  name: clickhouse
spec:
  ports:
  - name: http
    port: 8123
    targetPort: 0
  - name: tcp
    port: 9000
    targetPort: 0
  selector:
    app: clickhouse
  type: ClusterIP