apiVersion: v1
data:
  CLICKHOUSE_USER: postgres
  CLICKHOUSE_PASSWORD: postgres
  CLICKHOUSE_DB: postgres
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_SERVICE_NAME: clickhouse
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: clickhouse
  name: clickhouse