apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  serviceName: clickhouse
  template:
    metadata:
      annotations: {}
      labels:
        app: clickhouse
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: clickhouse
        image: '{{ .Values.images.clickhouse }}'
        imagePullPolicy: IfNotPresent
        name: clickhouse
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: tcp
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: clickhouse-data
        - mountPath: /var/log/clickhouse-server
          name: logs
      terminationGracePeriodSeconds: 180
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi