apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: nats
  name: nats
spec:
  ports:
  - name: tcp
    port: 4222
    targetPort: 0
  - name: http
    port: 8222
    targetPort: 0
  selector:
    app: nats
  type: ClusterIP