apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations: {}
  labels:
    app: pg
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  serviceName: pg
  template:
    metadata:
      annotations: {}
      labels:
        app: pg
    spec:
      containers:
      - args: []
        envFrom:
        - configMapRef:
            name: pg
        - secretRef:
            name: pg
        image: '{{ .Values.images.pg }}'
        imagePullPolicy: IfNotPresent
        name: pg
        ports:
        - containerPort: 5432
          name: tcp
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: apphost-feed4158f1-pg-data
      terminationGracePeriodSeconds: 180
  volumeClaimTemplates:
  - metadata:
      name: apphost-feed4158f1-pg-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi