name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/Argon.Api/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/Argon.Api/**'

jobs:
  build:
#    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY }}
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PWD }}
    - name: Build and push images
      run: |
        export DOCKER_DEFAULT_PLATFORM=linux/arm64
        export IMAGE_TAG=$(date +%s)
        docker buildx ls
        docker buildx inspect
        docker buildx build --platform=linux/aarch64 -t ${{ secrets.REGISTRY }}/argongg/api-orleans:$IMAGE_TAG -f ./src/Argon.Api/Dockerfile . --push
#        docker tag ${{ secrets.REGISTRY }}/argongg/api:$IMAGE_TAG ${{ secrets.REGISTRY }}/argongg/api:latest
#        docker push ${{ secrets.REGISTRY }}/argongg/api:latest