name: Canary

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**/**'
  workflow_dispatch:


jobs:
  build-ghcr:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ARGON_GHCR_PAT }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/Argon.Api/Dockerfile
          push: true
          tags: ghcr.io/argon-chat/orleans:nightly.${{ github.run_number }}
